---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agent-github-secret
  namespace: ai-agentic
spec:
  encryptedData:
    GITHUB_TOKEN: AgBW2tuJacHuwujfEx8A8pDTNSCJn1aur74LRkXNhyVILpkBPV069CMt7Rvo6FCDubb3p7iKqgNUJOh24fbN/zuCpyS00EuwvOQ7Obu4zhhRIIlTUrwywAb2kgnXS6ZhVjC7dqlHD5Xqapx6fOkmCvq5pCErOWanEtEtjjGRFVotk+5FupPcp6EzRvyZYoUxMnz6+/bStMn0qEZvzm1z33njlE/f+L6B/uN3bIEA90/fOX/rkcIet398PebDNy+Jz7kmGUnifJxqyf+N6I3+HDJwkRWwly1JdgclONHA6TeHiARCZezysqxaSbsBit+D7xW/oI20eKrNRQZtpVTzfCytC4xvyiSmMrkQ7NiNcPmHpV7w2yLObK4bzH0WlDS0b4hfbK21iVmpbT64LdM8BDxeWAHUw6SGv5BYthqNvC6WZmde/pl+f0EgM2LRVYjHGit9HJ2hejv8VXbEPhyO6Cl+SnTmb4nAqguhe3MjXAYEgtQKHHTBMAcsnvj+9sjlCcp0hqlMbUlemXkym+OFpA3+cLbevMj/GQpaadm4T+Q86mxwA+Jk7g7fSV+keK0tNxQiNZwdNKRqgM2s71ir9l0stqRIUSnEgiXwLQ+MnvPKWp+RIaWFFwcA12IjuCfsfHcyNCIqTp8HAJ4bDABhJaFOXzC0B04cV0aPUlx9S5LNyiy4G6wk6d2/PoW5OWke0ol1anh9c3HhaBQThBP//Qhp/kR86F6/pmDvlZTzEQCj49RtuaFXt4pA
  template:
    metadata:
      name: agent-github-secret
      namespace: ai-agentic
