---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: edubois10-aiagent-pull-secret
  namespace: ai-agentic
spec:
  encryptedData:
    .dockerconfigjson: AgBstKJOYwDObOPIPYM6eDth5Ph2VM9B4F2rzAzDAlSrsYHOEZ3/0Xs0aKqqzDBG2kFUYqbTI1GUeNSiUPrPHIDRmEV8nwOebDCh3IoygejfVzmeitjY06iRbyTWMnyU58BmCFdDlRwyFCzvSQWWAtpqEEFJhH9KermaeoGWewLwXPxuLp9+qme/H5EMXSTrM4ZySLX4PgVwNfOCS+udLbzVYjC0Z6TDnDt4fy7AHETAbUh7/FQ8BncJFHBLN7rwklzjQwkztrDFFWRk9ItNrCTnKOxMymwVY0CGX/YeC0P05DQkqIKvDUWfTISdsSKvLi6PmmzOkUJOUHpAw8HWnf7PNmjpV61vRfUILGbrrBZFYwBa+QP9USti9fxzbAn0yCCEK7TgO/pjZDIlZDrdjspzpXTqFWoI0r1i1WPq8PAWESkcpsswXKoqiRLiqKLjOlioAVkn5R+CwW0DyfdX5eLyVMbc4Da6q9ycDkfzanoT36zcalG4ivfDzAAbZ7DZAegAzTKIZf1RRb4qOgGRL6x769vhalzCjin5Oy0oNoVBAMxD8cY0eFKHaAYDZQw+i6GWpRKbTdsZZASFGNkktV9hK23dnpah36iG7jPA5kheHz61Fay6TmixxdTqhUCVFyyfUrlRI/4YiRxCkC3pn8i/Hdtb6aTTaaOb8QmeaXn+Ju5RhyrbkykXJBibW2i1Rfbz+DlRiPWxAuWRHVGk/CBgU/cc85mFhj3MrWDZQCPFinyl1cGPktltQP2G2gcSkgK1rrquamDyUrzYRCwF1CRY1dK8sSwGnk4k2Z1R0aPQBkgDyhxJZ22XQnY62nSECyQZkr15KABTkeyyselV66YJvlc6juFOPLetQUQKNwzlmSSeJy/BH6dF0GPETAxwHPlFp9QDDB4QeCucnAO6ZdVFcxqvxacrbzk7/WR/s/GW17rXuA2e4yNym5PAL7KHMjLTu05gYYMf7g==
  template:
    metadata:
      name: edubois10-aiagent-pull-secret
      namespace: ai-agentic
    type: kubernetes.io/dockerconfigjson
