---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: edubois10-aiagent-pull-secret
  namespace: ai-agentic
spec:
  encryptedData:
    .dockerconfigjson: AgBax9bKCkUXXZHWzmSQ9VmKki5d7Zg/N8l3gVFKMfnsKI3PE+mr9hWrGI4LJ7oRw8HOqfzXfFLMTZzay3+KoxH5MF5ywCNJjS//9x+PHsRVRMN4u00DV+hRCl7FSx+D4gpYKeVvit3pUuTWfCKELCqTo80ml+Qk5afDAiPXuadJ/jwxme7IS82ZhdV+cDLGbxJg5zz2F+At0DwBPVTp7vhqzPUb/HaTt5HIb2LVA9HInF/pnU6yNjg8Sr+OthmV5sCxns9jMz0B2Okiy0g0OPpeLBlmtSUeqx8aFhMh4MPyV7u685UQWc1hlviY4J6OqMCtzrFO873azQ3KBvKHUMFKm4GofpsXbpxdKkBnSKwt9UihQ53QzNRIhnTV9tszdPU39rekLYoGvKqFJP68rv/aFbfS4CikMTpAiM8c2q3fWCJyBFQ45UKxjqek2vxzWQx+pn+SmJzj1rVF+rhOP89ZrtccIHycOtEPTIL3CbVsOr/CfG8My+thiW7TllA1XJzdprCQY+G2TDOZbTSLX3HfwGOVAFiBb4XAuV4YdHykqmduI0KjelbDJSdHCJx17p2QDDLB6zcjc62kviDugHNNAyaCj2jUp4+1xN0ALa3UAwVF9om6ySyE/n40Bt+ps87pagTtuvtw3HlFnSnZbT5So+Jv+/bT/KrfhFz0il2FGXEPBusx886t9N7ZvBXdEEInhJZ8bpeicpGGUaCbaPUb08NjT8tGY8tMyVISOG8PlZAzD3FrJjColCUEEdX5g+Q8Bvs2TBR3NJwWuz/CKH7+3DOn+MUZ/UgNcvOByw8K588Tg0XoqrmBpA3OvVhL5O1gOmatFWee63p6wbgGKVV5JDOV0paF2V8NUxt5q++DapaNDuyBpKgsDAXRRztbNQIFpdEs4/yhtnyH7yYn7AfLiD6n2odauuKFjeMaOV3Y53wsOydz6eJcJboVHO6jKpk=
  template:
    metadata:
      name: edubois10-aiagent-pull-secret
      namespace: ai-agentic
    type: kubernetes.io/dockerconfigjson
