---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hf-token
  namespace: ai-agentic
spec:
  encryptedData:
    token: AgByJ8vO35BaMdHpzuACQiYHstK2695SgGLc3mVS08AL34+0AL2281yLppadx0WdpWGDTIN6IsU2ym2EmVYcHzY5ujAF/1mhRpLv5vioaVH5rPqsvPC5FAKRFOCsLKcL+omK51K4OVSELejp73uUfdf6QtZ4bXzLEveCoaNPnABooq1G9k+7yAhhRU2EOShCaL2+B3YOWnFHAUTgkTSpY0MNuJgRCEsqVfr4+fPKwzF8QhwHC215any7L7GJ5P6aVlAa6vq6j6+Sk2j6XoSoqtH/Beze6s1s+Yp9f6zCp6VTrsx1Kro9mmRZyjs9CjIYAw3hORVcdyWtqjLlnTf14qlCpHGOlT2y/3uhbifi4zq426LZgtAkmGYMMt7tRypdBOy4Yy1W6QaWqooDqh8Tedsd4Lf54ZZ4PD5Iy/nwqxTia5t2ELcTnnUjZsgLhnam4sSNW33U1KOxCsjFM+hP3yFLd67/MKiaGtuKzatqIFNB7CjhsvIM+K1+isBPm0JJFuXtOVZgIddpqQPVORcqrOKw0DWadFjx77tLlRWM0RECQQ8MLaU1mAQ8YDdp9AQjqa4YbsgezzXLPM78E0JcWCQIKldSCbOoXodvbOrP103hG3xiP14NEVxiJLMhjgbAkxQIguHTnjkfIh4K/uX7iUeFBONnd+HytEJX2CHmL61EiH5cZc0OQU4fZPwRmUvL4LCoKgP41mW2ttprV5k6QvZ0I1pAmX+tNWCv0wFTm5oWqDLPSQEs
  template:
    metadata:
      name: hf-token
      namespace: ai-agentic
