---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hf-token
  namespace: ai-agentic
spec:
  encryptedData:
    token: AgCgxT3UoLe7fUIUDS5ynczR7LNkEsDN5aybMpRWE4FN8RBuzZ2CP+r+fyzCoevwbcup3UgVqZZwaVt2f/Cdxz4jDUrsGQsDi5epq5EuhMiYDud2E0CW6/6BUrswfgr7NE14GxhuMPUBUb44PewSNlaEvZ+mtZ6D/OWCQSdTE/9Xx12Af3q+nwySGg0IT/0vZDT0/wLtCaYPQtbwsiwiCOoF2ea1YNjS6t4YNh4u9Wa7j+mGNE/+ukmcdMscDD4PmEn6yP1jGgngHwWTpiVH9y1bzM9l3d9kQwVNQja9NacauCB0V1YVQR6oxcQnC3KdQswonVBZeBa6XnHsO7HcSxTk7len5q7v0UxDowDn5U9DznqTkicgY6b1vQ+BkTAhPAh/BcT/9LNETZ+uhy9rHsY6MvG9diduk46FmsKDGV2B1Xa0Gb+ofA3KI2CNwIlMLuV15JummOQ/sYBcvguRGwaxEu36o52WwDgzBUKjMquO9cMyLdsbeqG5mCHAOrj8iOhm6guqZzA/TVRj8G8Z3mNRGcBKny5YGUiYZKm/GhK3qfaF5s+0sqREXqpWYZ3rHd7hOzS1yLs4MYyBkuq6qf0QoH7x1zq65B6h0q6UeClIZ8qFUgg6dPZqzUeBzN6wL+oabBbaZS7ekDkgX4aFO+JYVrSVf6lDYgXCJe8KkDSVXdo0k/3MkYXRJqS0kUGX1qmg6HFvuEHM2/IOt/qHQpBwjrAMN3WzXgIfU9TWy2vQBhZOUzds
  template:
    metadata:
      name: hf-token
      namespace: ai-agentic
