---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hf-token
  namespace: ai-agentic
spec:
  encryptedData:
    token: AgClMgVrY2tj5RPdtmUiCWtY3QddykSsmknBkct1nHN1Bx/fsrcInFodyla9df/KIY7ybaOqnR/VO7kZwfSK+fZfzb7m5tgEdp3jyUfrV8syw/WQMt+pncTrWBdi9MsYYM5yJMtKITAYkmUXB5DnB2MlpFgkMaTgk1nSvXVcvLrQ2FuIJzXWn4gkv9fRC+yp1LXYGz8vuTFKHzh/CVZRCrFu0jqd7psHRUGy/eUz8ooHsl96GoVV2UF+spoJ8Emqs/E/S4/ms3NBivpnSXy7gDQouYHmTvtqi0f5AgGtgozzu/jgOVt/dm3sP3JWzYwW1B7QCkIi5Oknq4Jz+DMtQHBf7VQczqc5kekgSIv5JaHQovnCq8Jsf5T6s4mJ1vFGuFyd6gyIzRxA7opZi0M/jJo8/trfdCeVjb1XeuwOYPU8fzFNh51GN0BUX8EUoGW5AYB1JmCvYGcYsSW2gWfym0CmeG8s/6S62ZGw1/5cRKfEg6YnLtEjrwuNTPeHHhSEuUfr2zPIx5aVpBB3kBoMmP9BmA6LmXFVdPxZNH8fzfbM/SpJO4jvKbYlm9JEGsOxe+8bgeYWAzCGFFf+2TzPnoPUVeRZ4EeVk3jSNgQJWEYY2CGsFd1I3uB6XuLesYscr4FludEmo0Sg2KRt7hMuAnJ0WOqfLPQrbKU8nPprzLZBDQ/2FeAnNESJj8cjuYFKuRo=
  template:
    metadata:
      name: hf-token
      namespace: ai-agentic
