---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-agentic
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/Babas10/devops-ai-agentic
    targetRevision: main
    path: k8s/ai-agentic
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-agentic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
