---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/Babas10/devops-ai-agentic
    targetRevision: main
    path: k8s/rhoai/gpu
  destination:
    server: https://kubernetes.default.svc
    namespace: redhat-ods-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
